### ISSUE TITLE
Crash on screen on / screen off

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#19]
Crash log:
```
08-09 04:23:35.661 11049 13207 F libc    : Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xf2ff004000000001 in tid 13207 (Thread-18), pid 11049 (elzero.bravedns)
08-09 04:23:35.984 14998 14998 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-09 04:23:35.984 14998 14998 F DEBUG   : Revision: '0'
08-09 04:23:35.984 14998 14998 F DEBUG   : ABI: 'arm64'
08-09 04:23:35.985 14998 14998 F DEBUG   : Timestamp: 2020-08-09 04:23:35+0530
08-09 04:23:35.985 14998 14998 F DEBUG   : pid: 11049, tid: 13207, name: Thread-18  >>> com.celzero.bravedns <<<
08-09 04:23:35.985 14998 14998 F DEBUG   : uid: 10416
08-09 04:23:35.985 14998 14998 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xf2ff004000000001
08-09 04:23:35.985 14998 14998 F DEBUG   :     x0  0000007d913d5b08  x1  0000007d998ee7e0  x2  0000007e8ddd0600  x3  0000007d918f9a2c
08-09 04:23:35.985 14998 14998 F DEBUG   :     x4  000000000000076c  x5  0000007d918f9a44  x6  000000000000076c  x7  f2ff004000000001
08-09 04:23:35.985 14998 14998 F DEBUG   :     x8  00000000076c0000  x9  00000000076c0000  x10 0000000000000066  x11 000000000000007a
08-09 04:23:35.985 14998 14998 F DEBUG   :     x12 0000000000000001  x13 0000007d90e09c40  x14 0000000000000000  x15 0000007d91487475
08-09 04:23:35.985 14998 14998 F DEBUG   :     x16 0000007e8af068f0  x17 0000007e8aef8070  x18 0000007d54be6000  x19 0000007e8ddd0600
08-09 04:23:35.985 14998 14998 F DEBUG   :     x20 0000000000000014  x21 0000007d918f9630  x22 0000000000000000  x23 0000007d918f9a08
08-09 04:23:35.985 14998 14998 F DEBUG   :     x24 0000004000436c00  x25 0000007d918f9630  x26 0000007d9158b250  x27 0000000000000010
08-09 04:23:35.985 14998 14998 F DEBUG   :     x28 0000004000082f00  x29 0000007d90e09c00
08-09 04:23:35.985 14998 14998 F DEBUG   :     sp  0000007d90e09bc0  lr  0000007d913e50ac  pc  f2ff004000000001
08-09 04:23:35.986 14998 14998 F DEBUG   :
08-09 04:23:35.986 14998 14998 F DEBUG   : backtrace:
08-09 04:23:35.986 14998 14998 F DEBUG   :       #00 pc f2ff004000000001  <unknown>
08-09 04:23:35.987 14998 14998 F DEBUG   :       #01 pc 00000000005d70a8  /data/app/com.celzero.bravedns-spvz9uRBb9GpyyDC9xqYkA==/base.apk (offset 0x214000) (ip4_input+476)
08-09 04:24:56.036 15136 15136 E AndroidRuntime: FATAL EXCEPTION: main
08-09 04:24:56.036 15136 15136 E AndroidRuntime: Process: com.celzero.bravedns, PID: 15136
08-09 04:24:56.036 15136 15136 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.SCREEN_OFF flg=0x58200010 } in com.celzero.bravedns.service.BraveScreenStateReceiver@a18c932
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args.run(Unknown Source:2)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:883)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:100)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:214)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7682)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
08-09 04:24:56.036 15136 15136 E AndroidRuntime: Caused by: m.a
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at com.celzero.bravedns.service.BraveScreenStateReceiver.onReceive(:14)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
08-09 04:24:56.036 15136 15136 E AndroidRuntime:    ... 8 more
--------- beginning of system

```

And this log may be relevant which precedes the crash log:

```
08-09 21:19:44.968  1310  1878 D ConnectivityService: Removing iface tun0 from network 118
08-09 21:19:44.968   730  1281 D NetlinkEvent: Unknown ifindex 109 in RTM_DELADDR
08-09 21:19:44.991  1310  1878 E ConnectivityService: Exception in removeRoute: java.lang.IllegalStateException: android.os.ServiceSpecificException: No such device (code 19)
08-09 21:19:44.992  1310  1878 I chatty  : uid=1000(system) ConnectivitySer identical 1 line
08-09 21:19:44.993  1310  1878 E ConnectivityService: Exception in removeRoute: java.lang.IllegalStateException: android.os.ServiceSpecificException: No such device (code 19)
08-09 21:19:44.993  1310  1878 I Nat464Xlat: Android Xlat enabled is doXlat = true
08-09 21:19:45.082  1310  1878 D ConnectivityService: Adding iface tun0 to network 118
08-09 21:19:45.170  1310  1878 D ConnectivityService: Removing iface tun1 from network 118
08-09 21:19:45.170   730  1281 D NetlinkEvent: Unknown ifindex 110 in RTM_DELADDR
08-09 21:19:45.196  1310  1878 E ConnectivityService: Exception in removeRoute: java.lang.IllegalStateException: android.os.ServiceSpecificException: No such device (code 19)
08-09 21:19:45.196  1310  1878 I chatty  : uid=1000(system) ConnectivitySer identical 1 line
08-09 21:19:45.197  1310  1878 E ConnectivityService: Exception in removeRoute: java.lang.IllegalStateException: android.os.ServiceSpecificException: No such device (code 19)
08-09 21:19:45.197  1310  1878 I Nat464Xlat: Android Xlat enabled is doXlat = true
08-09 21:19:45.598  1310  3078 E OPBF    : mImportantUids change mLastImportantUids =[10416, 10086, 10169, 10107, 10109] mImportantUids = [10416, 10086, 10107, 10109]
08-09 21:19:45.628  1310  3078 E OPBF    : mImportantUids change mLastImportantUids =[10416, 10086, 10107, 10109] mImportantUids = [10416, 10107, 10109]
08-09 21:19:45.754  1310  3078 E OPBF    : mImportantUids change mLastImportantUids =[10416, 10107, 10109] mImportantUids = [10416, 10109]
08-09 21:19:45.766  1310  1878 D ConnectivityService: Blocked status changed to true for 10107(168) on netId 118
08-09 21:19:45.766  1310  1878 D ConnectivityService: Blocked status changed to true for 10107(169) on netId 118
08-09 21:19:45.766  1310  1878 D ConnectivityService: Blocked status changed to true for 10107(170) on netId 118
08-09 21:19:45.767  1310  1878 D ConnectivityService: Blocked status changed to true for 10107(171) on netId 118
08-09 21:19:47.474  1310  1415 D ExtBatteryStatsService: @@@@ awaitUninterruptibly in 80 ms
08-09 21:19:47.476  1310  1415 D ExtBatteryStatsService: ext-flush too soon, skip
08-09 21:19:48.650 29985 30518 F libc    : Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xedca004000000001 in tid 30518 (Thread-23), pid 29985 (elzero.bravedns)

```

**Comment by ignoramous** [comment]
[vv4.txt](https://github.com/celzero/brave-android-app/files/5055985/vv4.txt)

The crash is usually following a call (and a subsequent device lock/unlock and/or a network connect/disconnect) which triggers a `restartVpn` by the app resulting in this crash.

**Comment by ignoramous** [comment]
The suspects are currently connection `close` in `intra.tcp#Handle` and `intra.udp#Connect` when `settings.BlockMode` is either `BlockModeFilter` or `BlockModeSink`.

**Comment by hussainmohd-a** [comment]
Logs from the test run : 

2020-08-12 19:09:27.038 29086-29086/com.celzero.bravedns D/BraveDNS: Block Traffic : 1
2020-08-12 19:09:27.038 29086-29086/com.celzero.bravedns D/BraveDNS: Restart VPN - DNSMode: 2, FirewallMode: 2 
2020-08-12 19:09:27.038 29086-29086/com.celzero.bravedns D/BraveDNS: Builder creation started VPN - builder
2020-08-12 19:09:27.040 29086-29151/com.celzero.bravedns D/BraveDNS: uid : 10094, packageName: com.android.chromeSource : 10.111.222.1:49318, Destination: 138.197.192.84:443, protocol : 6
2020-08-12 19:09:27.043 29086-29086/com.celzero.bravedns D/BraveDNS: Builder creation completed ***  VPNService establish is called from builder
2020-08-12 19:09:27.108 29086-29086/com.celzero.bravedns D/BraveDNS: tunFd received from VPNService
2020-08-12 19:09:27.110 29086-29153/com.celzero.bravedns D/BraveDNS: uid : -1, packageName: nullSource : 10.111.222.1:49324, Destination: 138.197.192.84:443, protocol : 6
2020-08-12 19:09:27.111 29086-29170/com.celzero.bravedns D/BraveDNS: uid : -1, packageName: nullSource : 10.111.222.1:49322, Destination: 138.197.192.84:443, protocol : 6
2020-08-12 19:09:27.111 29086-29156/com.celzero.bravedns D/BraveDNS: uid : 10094, packageName: com.android.chromeSource : 10.111.222.1:34191, Destination: 10.111.222.3:53, protocol : 17
2020-08-12 19:09:27.115 29086-29151/com.celzero.bravedns D/BraveDNS: uid : 10094, packageName: com.android.chromeSource : 10.111.222.1:33644, Destination: 10.111.222.3:53, protocol : 17
2020-08-12 19:09:27.127 29086-30246/com.celzero.bravedns I/GoLog: failed to write UDP data to TUN
2020-08-12 19:09:27.199 29086-29086/com.celzero.bravedns D/BraveDNS: start connectTunnel --- DNS Mode: 2 Firewall Mode: 2
2020-08-12 19:09:27.199 29086-29086/com.celzero.bravedns D/BraveDNS: start connectTunnel - Before GoIntraListener
2020-08-12 19:09:27.199 29086-29086/com.celzero.bravedns D/BraveDNS: start connectTunnel - dohURL : https://dns.adguard.com/dns-query
2020-08-12 19:09:27.200 29086-29086/com.celzero.bravedns D/BraveDNS: start makeDohTransport - realUrl : https://dns.adguard.com/dns-query
2020-08-12 19:09:27.200 29086-29086/com.celzero.bravedns D/BraveDNS: start makeDohTransport - dohIPs : 
2020-08-12 19:09:27.206 29086-29086/com.celzero.bravedns D/BraveDNS: tunnel connected****
2020-08-12 19:09:27.206 29086-29086/com.celzero.bravedns D/BraveDNS: tunnel set to DNS mode : 2Firewall Mode:2
2020-08-12 19:09:27.208 29086-29155/com.celzero.bravedns I/GoLog: DoH query failed: connection closed
2020-08-12 19:09:27.210 29086-29153/com.celzero.bravedns A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x5a004000000001 in tid 29153 (Thread-17), pid 29086 (elzero.bravedns)

**Comment by hussainmohd-a** [comment]
Test Case: In the below case, the last connection is from System with uid : 1051, packageName: null, Source : 10.111.222.1:18002, Destination: 10.111.222.3:53, protocol : 17. 
Firewall mode is equal to 2. 

Logs:

2020-08-12 19:18:30.100 2188-2805/com.celzero.bravedns I/GoLog: failed to write UDP data to TUN
2020-08-12 19:18:30.130 2188-2805/com.celzero.bravedns D/BraveDNS: uid : 10049, packageName: com.android.chromeSource : 10.111.222.1:48493, Destination: 74.125.24.94:443, protocol : 17
2020-08-12 19:18:31.463 2188-2780/com.celzero.bravedns D/BraveDNS: uid : 10113, packageName: com.whatsappSource : 10.111.222.1:48748, Destination: 34.192.181.12:5222, protocol : 6
2020-08-12 19:18:31.823 2188-2188/com.celzero.bravedns D/BraveDNS: Block Traffic : 1
2020-08-12 19:18:31.823 2188-2188/com.celzero.bravedns D/BraveDNS: Restart VPN - DNSMode: 2, FirewallMode: 2 
2020-08-12 19:18:31.823 2188-2188/com.celzero.bravedns D/BraveDNS: Builder creation started VPN - builder
2020-08-12 19:18:31.826 2188-2188/com.celzero.bravedns D/BraveDNS: Builder creation completed ***  VPNService establish is called from builder
2020-08-12 19:18:31.896 2188-2188/com.celzero.bravedns D/BraveDNS: tunFd received from VPNService
2020-08-12 19:18:31.897 2188-2805/com.celzero.bravedns D/BraveDNS: uid : 10049, packageName: com.android.chromeSource : 10.111.222.1:25590, Destination: 10.111.222.3:53, protocol : 17
2020-08-12 19:18:31.897 2188-2375/com.celzero.bravedns D/BraveDNS: uid : 1051, packageName: nullSource : 10.111.222.1:18002, Destination: 10.111.222.3:53, protocol : 17
2020-08-12 19:18:31.973 2188-2188/com.celzero.bravedns D/BraveDNS: start connectTunnel --- DNS Mode: 2 Firewall Mode: 2
2020-08-12 19:18:31.973 2188-2188/com.celzero.bravedns D/BraveDNS: start connectTunnel - Before GoIntraListener
2020-08-12 19:18:31.974 2188-2188/com.celzero.bravedns D/BraveDNS: start connectTunnel - dohURL : https://dns.adguard.com/dns-query
2020-08-12 19:18:31.974 2188-2188/com.celzero.bravedns D/BraveDNS: start makeDohTransport - realUrl : https://dns.adguard.com/dns-query
2020-08-12 19:18:31.974 2188-2188/com.celzero.bravedns D/BraveDNS: start makeDohTransport - dohIPs : 
2020-08-12 19:18:31.991 2188-2188/com.celzero.bravedns D/BraveDNS: tunnel connected****
2020-08-12 19:18:31.991 2188-2188/com.celzero.bravedns D/BraveDNS: tunnel set to DNS mode : 2Firewall Mode:2
2020-08-12 19:18:32.925 2188-2375/com.celzero.bravedns A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xf7a8004000000001 in tid 2375 (Thread-19), pid 2188 (elzero.bravedns)
2020-08-12 19:18:33.993 2188-2188/com.celzero.bravedns D/BraveDNS: Resume Traffic : 1
2020-08-12 19:18:33.993 2188-2188/com.celzero.bravedns D/BraveDNS: Restart VPN - DNSMode: 2, FirewallMode: 1 
2020-08-12 19:18:33.993 2188-2188/com.celzero.bravedns D/BraveDNS: Builder creation started VPN - builder
2020-08-12 19:18:34.000 2188-2188/com.celzero.bravedns D/BraveDNS: Builder creation completed ***  VPNService establish is called from builder
2020-08-12 19:18:34.074 2188-2188/com.celzero.bravedns D/BraveDNS: tunFd received from VPNService

**Comment by ignoramous** [comment]
It looks like we may be creating a new tunnel before disconnecting the previous one: [com/celzero/bravedns/service/BraveVPNService.kt#L488-L489](https://github.com/celzero/brave-android-app/blob/d6ee8be7618d17a92f88e34857c750ace3fdd626/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L488-L489).

Swapping (disconnecting the previous tunnel before creating a new one) has eliminated the crash in our tests (which were frequent). Hopefully that's the end of that.
