### ISSUE TITLE
ANR in ScreenLockService

### ISSUE THREAD

**Issue by ignoramous** [celzero/brave-android-app#22]
[anr_2020-08-14-00-46-01-940.txt](https://github.com/celzero/brave-android-app/files/5074279/anr_2020-08-14-00-46-01-940.txt)

```
08-14 00:46:01.835  1202  1411 W ActivityManager: Timeout executing service: ServiceRecord{f4bea7d u0 com.celzero.bravedns/.receiver.ScreenLockService}
```

From ANR report:

1. The ANR happens when `ScreenLockService` tries to `GoVpnAdapter#close` but couldn't get the `lock` (the method is `synchronized` on the instance object:
```
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x72f59a78 self=0x700b406c00
  | sysTid=17118 nice=0 cgrp=default sched=0/0 handle=0x700c974ed0
  | state=S schedstat=( 22272983905 2779119802 17008 ) utm=2004 stm=223 core=6 HZ=100
  | stack=0x7ffd049000-0x7ffd04b000 stackSize=8192KB
  | held mutexes=
  at com.celzero.bravedns.net.go.GoVpnAdapter.close(GoVpnAdapter.java:-1)
  - waiting to lock <0x056e5b6f> (a com.celzero.bravedns.net.go.GoVpnAdapter) held by thread 46
  at com.celzero.bravedns.service.BraveVPNService.restartVpn(BraveVPNService.kt:511)
  - locked <0x06b2f07c> (a com.celzero.bravedns.service.VpnController)
  at com.celzero.bravedns.service.BraveVPNService.blockTraffic(BraveVPNService.kt:90)
  at com.celzero.bravedns.receiver.ScreenLockService.checkLock(ScreenLockService.kt:69)
  at com.celzero.bravedns.receiver.ScreenLockService.onStartCommand(ScreenLockService.kt:32)
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4204)
  at android.app.ActivityThread.access$2100(ActivityThread.java:231)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1984)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7682)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

2. But the lock is held by `tid 46` stuck at `GoVpnAdapter#updateDohUrl` -> `Tun2Socks#newDoHTransport` run in response to `NETWORK_CONNECTED` broadcast:

```
"startVpn-onNetworkConnected" prio=5 tid=46 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x12f4f118 self=0x700b58a000
  | sysTid=19256 nice=0 cgrp=default sched=0/0 handle=0x6f26af9d50
  | state=S schedstat=( 748333 2309063 5 ) utm=0 stm=0 core=6 HZ=100
  | stack=0x6f269f7000-0x6f269f9000 stackSize=1039KB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/19256/stack)
  native: #00 pc 00000000002ae47c  /data/app/com.celzero.bravedns-u5kHoa7fG6gUWrYWidCctA==/base.apk (offset 1f3000) (???)
  at tun2socks.Tun2socks.newDoHTransport(Native method)
  at com.celzero.bravedns.net.go.GoVpnAdapter.makeDohTransport(GoVpnAdapter.java:220)
  at com.celzero.bravedns.net.go.GoVpnAdapter.updateDohUrl(GoVpnAdapter.java:255)
  - locked <0x056e5b6f> (a com.celzero.bravedns.net.go.GoVpnAdapter)
  at com.celzero.bravedns.service.BraveVPNService.updateServerConnection(BraveVPNService.kt:364)
  at com.celzero.bravedns.service.BraveVPNService.access$updateServerConnection(BraveVPNService.kt:55)
  at com.celzero.bravedns.service.BraveVPNService$onNetworkConnected$1.run(BraveVPNService.kt:541)
  at java.lang.Thread.run(Thread.java:919)
```

One probable solution (a workaround really) is to use a `android.os.Handler` to deal with communication happen from a service-thread aloof from `BraveVPNService`, like in [androidxref.com/SystemUI/src/com/android/systemui/keyguard/KeyguardViewMediator.java](http://androidxref.com/9.0.0_r3/xref/frameworks/base/packages/SystemUI/src/com/android/systemui/keyguard/KeyguardViewMediator.java).

**Comment by hussainmohd-a** [comment]
Universal app firewall logic is modified from setting the VPN into sink mode to filter mode. When the block all apps configuration is enabled, filter mode will return true for all the apps which will block the apps from connecting to internet
